### ISSUE TITLE
Localization bug in menu, breadcrumbs, title

### ISSUE THREAD

**Issue by arturtr** [activeadmin/activeadmin-mongoid#40]
In my locale file I have:

```
ru:
  mongoid:
    models:
      admin_user: Админ
      page: Страница
      photo: Фото
      work_item: Вид работ
    attributes:
      work_item:
        work_type: Вид услуг
        name: Наименование
      photo:
        title: Примечание
        image: Файл с фотографией
```

It work great, but header menu, breadcrumbs, system buttons ( **Add ...**, **Edit ...** tried to use `ru.activerecord.models.*`.

I can fix it with duplicating locale data for active record:

```
ru:
  activerecord:
    models:
      admin_user: Админ
      page: Страница
      photo: Фото
      work_item: Вид работ
```

But I think that is not so good. I tried to find the bug in the source code, but I found none.
